config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  resources :cards do
    member do
      put :move
    end
 
  end
  
  # /lists/2/move
  resources :lists do 
    member do
      put :move
    end
  
  end

  root 'lists#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  
  acts_as_list scope: :list

  belongs_to :list

  validates :name, presence: true
  
end

app/models/list.rb
class List < ApplicationRecord
  
  acts_as_list scope: :user

  belongs_to :user
  has_many :cards, -> {order(position: :asc)}, dependent: :destroy

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :lists, -> {order(position: :asc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  before_action :set_card, only: %i[ show edit update destroy move ]
  #skip_before_action :verify_authenticity_token
  
  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  def move
    # render json: card_params  #{list_id: "5", position: "2"}
    @card.update(card_params)
    render "show.json"
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        ActionCable.server.broadcast "board", {commit: 'REPLACE_CARD', payload: render_to_string(:show, format: :json)}
        format.html { redirect_to @card, notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :list_id ,:position)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [ :show, :edit, :update, :destroy, :move]
  before_action :authenticate_user!

  # GET /lists or /lists.json
  def index
    @lists = current_user.lists.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = current_user.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    
    @list = current_user.lists.new(list_params)

    # render json: params

    respond_to do |format|

      if @list.save

        ActionCable.server.broadcast "board", {commit: 'ADD_LIST', payload: render_to_string(:show, format: :json)}

        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update

    #render json: params
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    ActionCable.server.broadcast "board", {commit: 'REMOVE_LIST', payload: render_to_string(:show, format: :json)}

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def move

    # Test
    # render json: params

    # render json: params[:lists][:position]
    # render json: list_params[:position]
    @list.insert_at(params[:lists][:position].to_i)
    render "show.json"

  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :position)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>List</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.list_id %></td>
        <td><%= card.position %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>List:</strong>
  <%= @card.list_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @card.position %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" if notice %>
    <%= yield %>
  </body>

</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<!-- <div class="flex py-5">
  
  <% @lists.each do |list| %> 
    <div class="bg-gray-300 mx-2 w-64 rounded text-center">
      <h2 class="px-3 py-2 font-thin"><%= list.name %></h2>
    </div>
  <% end %>

</div> -->

<div id ="board" class="py-5" >
  
  <draggable class="flex" v-model="lists" @change="MoveList" >
   
    <List v-for="list in lists" :list ="list" :key="list.id"></List>
    <Newlist></Newlist>

  </draggable>
</div>


<!-- data-lists=" @lists.to_json(include: :cards) " -->

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @list.position %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/shared/_flash.html.erb
<div class="bg-blue-100 px-3 py-2">
    <i class="far fa-bell mr-1 text-blue-600"></i>
    <span class="bg-blue-100 px-3 py-2 text-blue-600"><%= notice %></span>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-blue-500 px-3 py-5 text-2xl font-bold text-blue-100 flex justify-between">
    
    <!-- logo -->
    <a href="/">
        <i class="fab fa-trello"></i>Trello
    </a>
    
    <!-- 登入 / 註冊 / 登出 -->
    <div>
        <% unless user_signed_in? %>
            <%= link_to "登入", new_user_session_path, class:"user-button" %>
            <%= link_to "註冊", new_user_registration_path, class:"user-button"  %> 
        <% else %>
            <span><%= current_user.email %></span>
            <%= link_to "登出", destroy_user_session_path, method:"delete", data: {confirm: "確定登出？"}, class:"user-button"  %>   
        <% end %>
    </div>

</nav>